#!/bin/bash

#!/bin/bash
#wh:5
declare -a OsszesEsemeny=("Ápr-21-22=>Op.beadandó" "Ápr-24-25-26=>Webprog.beadandó" "Ápr-29=>Kalk.Zh." "Máj-1-2-3=>Tanulás:Kalk.,Dimat.,Webprog.,Algo.,Magprog.Zh.-ra" "Máj-5=>Op.Zh." "Máj-6=>Dimat,Kalk.Zh."
 "Máj-7=>Webprog,Algo.Zh."
 "Máj-11=>Vizsgajelentkezés"
 "Máj-16=>Vizsgaidőszak")

clear
echo "Üdv itt tekinthetőek meg a tavaszi események: "
echo""

cal -A 1

while [ true ]
do
        echo "Írj 1 est a legközelebbi esemény megjelítéséhez"
        echo "Írj 2 est az összes esemény megjelenítéséhez"
        echo "Írj 3 ast új esemény hozzáadásához"
        echo "Nyomj ENTER-t a kilépéshez"
        read
        case "$REPLY" in
                1)
                echo "A legkozelebbi esemény:"
                echo ${OsszesEsemeny[0]}
                ;;
                2)
                echo "Az összes esemény:"
                        for esemeny in ${OsszesEsemeny[@]}
                        do
                        echo $esemeny
                        done
                ;;
                3)
                echo "Add meg az új eseményt:"
                read OsszesEsemeny[-1]
                echo "Az új esemény a naptárba került."
                ;;
                *)
                echo "Nem megfelelő menüpontot, ENTER-t nyomtál, a naptár beztárul..."
                exit 0
                ;;
        esac
        echo ""
done

